#!/bin/bash
set -e

production=false

echo "Deploying master..."

dc="docker-compose -f docker-compose.yml -f staging.yml"

if [ "$production" = true ] ; then
	echo "Deploying to production."
	read -p "Are you sure? [yY]" -n 1 -r
	if [[ ! $REPLY =~ ^[Yy]$ ]]
	then
		echo "Aborting deploy"
		exit 1
	fi
	dc+=" -f production.yml"
fi

# Update checkout
GIT_WORK_TREE=/srv/live git checkout -f master
cd /srv/live

# Update post-receive
cp /srv/live/post-receive /srv/live.git/hooks/post-receive

# Rebuild docker
docker network create live_default || true
$dc create
$dc start

# Reload nginx
$dc kill -s SIGHUP web

# Reset permissions
sudo chown -R :adm /srv/live
sudo chmod -R g+rwX /srv/live
