#!/bin/sh

# Docker compose bases the project name on the directories base name and mangles
# it in an undocumented way.
project=$(basename $(pwd) | tr [:upper:] [:lower:])

# Rebuild single instance
if [ "$#" -eq 1 ]; then
	echo "Rebuild" $1
	docker-compose stop $1
	docker-compose rm -f $1
	docker-compose create --force-recreate $1
	docker-compose start $1
	exit
fi

echo "Rebuild all"
docker network create "${project}_default"

docker-compose stop
# sudo rm -rf data/data
docker-compose rm -f
docker-compose create
docker-compose start

# PostgREST fails on start if PostgreSQL is not up and running,  restart it
docker-compose stop api
docker-compose start api
